[package]
name = "components"
version = "0.1.0"
authors = ["Daniël Louwrink <daniel.louwrink@gmail.com>"]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["oleauto", "combaseapi", "objbase", "windef"] }
failure = "0.1"
failure_derive = "0.1"
